/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.betappmaven.Vista;

import com.mycompany.betappmaven.DAO.Login;
import com.mycompany.betappmaven.DB.Pool;
import com.mycompany.betappmaven.Modelo.Apuesta;
import com.mycompany.betappmaven.Modelo.Jugador;
import com.mycompany.betappmaven.Modelo.Partido;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Labin
 */
public class MisApuestas extends javax.swing.JFrame {

    /**
     * Creates new form MisApuestas
     */
    public MisApuestas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableMisApuestas = new javax.swing.JTable();
        jButtonVerApuestas = new javax.swing.JButton();
        jButtonVolver = new javax.swing.JButton();
        jButtonModificarApuest = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTableMisApuestas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "idPartido", "localia", "Visitante", "Jugado", "HoraInicio", "marcadorLocal", "marcadorVisitante"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableMisApuestas);

        jButtonVerApuestas.setText("VerApuestas");
        jButtonVerApuestas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVerApuestasActionPerformed(evt);
            }
        });

        jButtonVolver.setText("Volver");
        jButtonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVolverActionPerformed(evt);
            }
        });

        jButtonModificarApuest.setText("Modificar Apuesta");
        jButtonModificarApuest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModificarApuestActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(120, 120, 120)
                                .addComponent(jButtonVerApuestas)
                                .addGap(304, 304, 304)
                                .addComponent(jButtonVolver))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(296, 296, 296)
                                .addComponent(jButtonModificarApuest)))
                        .addGap(0, 123, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonVolver)
                    .addComponent(jButtonVerApuestas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonModificarApuest, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
            Pool metodospool = new Pool();
            Login log = new Login();
    private void jButtonVerApuestasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVerApuestasActionPerformed
        int a=log.acceder();
                
        Connection conect = null; 
        String query =("SELECT partido.idPartido,partido.localia, partido.visitante, partido.jugado, partido.horaInicio, Apuesta.marcadorLocal, Apuesta.marcadorVisitante FROM Partido right join Apuesta using(idPartido) right join Jugador using(idJugador) where idjugador='"+a+"';");
        try {
            
            conect = metodospool.dataSource.getConnection();
            DefaultTableModel dtm = new DefaultTableModel();
            jTableMisApuestas.setModel(dtm);
         
            PreparedStatement ps = conect.prepareStatement(query);
            ResultSet rs = ps.executeQuery();
            ResultSetMetaData rsm = rs.getMetaData();
            int columnas = rsm.getColumnCount();
            
            dtm.addColumn("idPartido");
            dtm.addColumn("localia");
            dtm.addColumn("visitante");
            dtm.addColumn("jugado");
            dtm.addColumn("horaInicio");
            dtm.addColumn("marcadorLocal");
            dtm.addColumn("marcadorVisitante");
            
            jTableMisApuestas.getColumnModel().getColumn(1).setPreferredWidth(95);
            jTableMisApuestas.getColumnModel().getColumn(2).setPreferredWidth(95);
            jTableMisApuestas.getColumnModel().getColumn(4).setPreferredWidth(150);

            
            while(rs.next()){
                Object[] filas = new Object[columnas];
                for(int i=0; i<columnas; i++){
                    filas[i] = rs.getObject(i + 1);
                }
                dtm.addRow(filas);
            }
            
        } catch (SQLException ex) {
            System.err.println(ex.toString());
        }
        
    }//GEN-LAST:event_jButtonVerApuestasActionPerformed

    private void jButtonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVolverActionPerformed
        Menu men=new Menu();
        men.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonVolverActionPerformed

    private void jButtonModificarApuestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModificarApuestActionPerformed
        
        int seleccion;
        int idJugador=log.acceder();
        seleccion=jTableMisApuestas.getSelectedRow();
        if(seleccion!=-1){
        Partido partido=new Partido();
        Apuesta apu=new Apuesta();
        ModificarApuesta mod=new ModificarApuesta();
        mod.jLabelActivo.setText(jTableMisApuestas.getValueAt(seleccion, 3).toString());
        mod.jLabelidPartido.setText(jTableMisApuestas.getValueAt(seleccion, 0).toString());
        mod.jLabelLocal.setText(jTableMisApuestas.getValueAt(seleccion, 1).toString());
        mod.jLabelVisitante.setText(jTableMisApuestas.getValueAt(seleccion, 2).toString());
        this.dispose();
        mod.setVisible(true);
        }else{
            JOptionPane.showMessageDialog(null, "no ha seleccionado ningun dato");
        }
    }//GEN-LAST:event_jButtonModificarApuestActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MisApuestas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MisApuestas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MisApuestas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MisApuestas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MisApuestas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButtonModificarApuest;
    public javax.swing.JButton jButtonVerApuestas;
    public javax.swing.JButton jButtonVolver;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable jTableMisApuestas;
    // End of variables declaration//GEN-END:variables
}
